(ert-deftest runned-services-test ()
  (flet ((emamux-rt:project-root () "/a/b/c"))
    (emamux-rt:add-service "/a/b/c" 'serv nil)
    (should (emamux-rt:service-alive-p 'serv))
    (emamux-rt:remove-service "/a/b/c" 'serv)
    (should (null (emamux-rt:service-alive-p 'ser)))))

(ert-deftest service-pane-id-test ()
  (flet ((emamux-rt:project-root () "/a/b/c"))
    (emamux-rt:add-service "/a/b/c" 'serv "%4")
    (emamux-rt:add-service "/a/b/c" 'dumb nil)
    (should (equal "%4" (emamux-rt:service-pane-id 'serv)))
    (should (null (emamux-rt:service-pane-id 'dumb)))))
